## Упражнения по библиотеке Numpy

In [200]:
import numpy as np
import itertools

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [201]:
# your code
def f1(a):
    a[(a > 3) & (a < 8)] *= -1
    return a
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(f1(a))

[ 1  2  3 -4 -5 -6 -7  8]


**2.** Заменить максимальный элемент случайного массива на 0

In [202]:
# your code
def f2(a):
    a[a.argmax()] = 0
    return a
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(f2(a))

[1 2 3 4 5 6 7 0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [203]:
# your code
def f3(a):
    result = np.array(list(itertools.product(*a)))
    return result
a = np.array([[1, 2], [3, 4]])
print(f3(a))

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [204]:
# your code
def f4(A, B):
    row_mask = np.ones(len(A), dtype = bool)
    for row in B:
        for col in row:
            mask = (A == col).any(axis = 1)
            row_mask = row_mask & mask
    return np.where(row_mask)[0]

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [3, 1, 2],
    [1, 2, 4]
])

B = np.array([
    [1, 2],
    [2, 3]
])

print(f4(A, B))

[0 2]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [205]:
# your code
def f5(A):
    A = A[A.min(axis = 1)!= A.max(axis = 1)]
    return A

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 7, 7]
])
print(f5(A))

[[1 2 3]
 [4 5 6]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [206]:
# your code
def f6(A):
    A = np.unique(A, axis = 0)
    return A

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

print(f6(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [207]:
# your code
def diag_product(A):
    result = 1
    rows = len(A)
    cols = len(A[0])
    n = min(rows, cols)
    for i in range(n):
        if A[i][i] != 0:
            result *= A[i][i]
    return result

def diag_product_np(A):
    diag = np.diag(A)
    result = np.prod(diag[diag != 0])
    return result

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [2, 3, 4]
])

print(diag_product(A))
print(diag_product_np(A))


15
15


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [208]:
# your code
def multiset(x, y):
    if len(x) != len(y):
        return False
    d = {}
    for elem in x:
        if elem in d:
            d[elem] += 1
        else:
            d[elem] = 1
    for elem in y:
        if elem not in d or d[elem] == 0:
            return False
        else:
            d[elem] -= 1

    return True

def multiset_np(x, y):
    result = np.array_equal(np.sort(x), np.sort(y))
    return result

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

print(multiset(x, y))
print(multiset_np(x, y))


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [209]:
# your code
def max_elem_np(x):
    good = x[1:][x[:-1] == 0]
    if good.size > 0:
        return np.max(good)
    else:
        return None

def max_elem(x):
    max_val = None
    for i in range(1, len(x)):
        if x[i-1] == 0:
            if max_val is None or x[i] > max_val:
                max_val = x[i]
    return max_val

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
a = np.array([6, 5, 7, 0])
b = np.array([6, 5, 7])

print(max_elem(x))
print(max_elem_np(x))
print(max_elem(a))
print(max_elem_np(a))
print(max_elem(b))
print(max_elem_np(b))


5
5
None
None
None
None


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [210]:
# your code
def rle(x):
    if len(x) == 0:
        return np.array([]), np.array([])
    keys = [x[0]]
    counts = []
    count = 1

    for i in range(1, len(x)):
        if x[i] == x[i-1]:
            count += 1
        else:
            counts.append(count)
            keys.append(x[i])
            count = 1
    counts.append(count)

    return np.array(keys), np.array(counts)

def rle_np(x):
    if x.size == 0:
        return np.array([]), np.array([])
    change_idx = np.where(x[1:] != x[:-1])[0] + 1
    sections = np.concatenate(([0], change_idx, [len(x)]))
    values = x[sections[:-1]]
    counts = np.diff(sections)

    return values, counts

x = np.array([2, 2, 2, 3, 3, 3, 5])
a = np.array([])
print(rle(x))
print(rle_np(x))
print(rle(a))
print(rle_np(a))


(array([2, 3, 5]), array([3, 3, 1]))
(array([2, 3, 5]), array([3, 3, 1]))
(array([], dtype=float64), array([], dtype=float64))
(array([], dtype=float64), array([], dtype=float64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [211]:
# your code
import math
from scipy.spatial.distance import cdist
import time

def dist(X, Y):
    result = []
    
    for x in X:
        row = []
        for y in Y:
            d = math.sqrt(sum((a - b) ** 2 for a, b in zip(x, y)))
            row.append(d)
        result.append(row)
    return result

def dist_np(X, Y):
    diff = X[:, np.newaxis] - Y
    result = np.linalg.norm(diff, axis=-1)
    return result

X_data = np.random.rand(1000, 10)
Y_data = np.random.rand(1000, 10)
X_list = X_data.tolist()
Y_list = Y_data.tolist()

start = time.time()
res_py = dist(X_list, Y_list)
print(f"Python: {time.time() - start:.4f}s")

start = time.time()
res_np = dist_np(X_data, Y_data)
print(f"NumPy: {time.time() - start:.4f}s")

start = time.time()
res_scipy = cdist(X_data, Y_data)
print(f"SciPy: {time.time() - start:.4f}s")

Python: 1.8617s
NumPy: 0.0724s
SciPy: 0.0053s


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [212]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [213]:
 
calorie_stats = np.loadtxt('cereal.csv', delimiter=',')

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [214]:
# your code
average_calories = np.mean(calorie_stats) - 60
print(average_calories)

46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [215]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [216]:
# your code
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [217]:
# your code
nth_percentile = -1
for i in range(1, 101):
    if np.percentile(calorie_stats, i) > 60:
        nth_percentile = np.percentile(calorie_stats, i)
        break
print(nth_percentile)


70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [218]:
# your code
more_calories = len(calorie_stats[calorie_stats>60]) / len(calorie_stats) * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [219]:
# your code
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [220]:
# your code